// Code generated by protoc-gen-go.
// source: distributed_write.proto
// DO NOT EDIT!

package message

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type DistributedWrite struct {
	Key              *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Data             *string `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DistributedWrite) Reset()         { *m = DistributedWrite{} }
func (m *DistributedWrite) String() string { return proto.CompactTextString(m) }
func (*DistributedWrite) ProtoMessage()    {}

func (m *DistributedWrite) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *DistributedWrite) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

func init() {
}
